### ISSUE TITLE
sanity check around input parameter of notifyRewardAmount(uint256 reward)

### ISSUE THREAD

**Issue by rayeaster** [harvest-finance/harvest#7]
in the https://github.com/harvest-finance/harvest/blob/master/contracts/RewardPool.sol#L753
a sanity value check around the resulting `rewardRate` needed?

say if by some mistake, the `rewardRate` is set to very very big value, then following call on modifier `updateReward` (specifically `rewardPerToken`) might get revert on `SafeMath.add` due to overflow?

**Comment by rayeaster** [comment]
hear from discrod Brandon Radar: this is already discussed and resolved
```
I believe the DelayMinter that's been implemented since does the check described in the issue https://etherscan.io/address/0x284d7200a0dabb05ee6de698da10d00df164f61d#code
```

**Comment by breadforthepeople** [comment]
Confirming that this is resolved.
